spring.application.name: service-registry
server.port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://${spring.application.name}:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: false
